### ISSUE TITLE
Tsc error when upgraded to 0.5.X from 0.4.X

### ISSUE THREAD

**Issue by takahiro-1227** [pmmmwh/react-refresh-webpack-plugin#780]
Hi!
When I upgraded to 0.5.X from 0.4.X, tsc transpile fail with this error. 
Please help me if you know something about it 🙇

```
../../node_modules/@types/webpack/node_modules/webpack/types.d.ts:1777:3 - error TS1131: Property or signature expected.

1777  	get normalModuleLoader(): SyncHook<[object, NormalModule]>;
      	~~~

../../node_modules/@types/webpack/node_modules/webpack/types.d.ts:1778:3 - error TS1109: Expression expected.

1778  }>;
       ~

../../node_modules/@types/webpack/node_modules/webpack/types.d.ts:1778:4 - error TS1109: Expression expected.

1778  }>;
.
.
.
```

`yarn webpack` have no problem.
```
"typescript": "4.1.3",
"react-refresh": "^0.14.0",
"webpack": "^5.89.0",
"webpack-cli": "^5.1.4",
"webpack-dev-server": "^4.15.1"
"@pmmmwh/react-refresh-webpack-plugin": "^0.5.11",
"@types/webpack": "^5.28.4",
```

tsconfig.json
```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "strict": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "preserveSymlinks": true,
    "skipLibCheck": true,
    "jsx": "preserve",
    "incremental": true,
    "isolatedModules": true,
    "module": "esnext",
    "noEmit": true,
    "target": "esnext"
  }
}
```

**Comment by takahiro-1227** [comment]
When upgraded typescript to `5.2.2`, this error did not happen !

**Comment by pmmmwh** [comment]
Issue seems to be `tsc` related / duplicate copies of the same dependency - let me know if this is still the case :)
