### PR TITLE
fix: add options to files

### LINKED ISSUE #354: Error: Cannot find module '../../options'
```
[webpack-cli] Error: Cannot find module '../../options'
Require stack:
- /Users/dh/Sites/wn/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/utils/normalizeOptions.js
- /Users/dh/Sites/wn/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/utils/index.js
- /Users/dh/Sites/wn/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js
```

@pmmmwh/react-refresh-webpack-plugin: 0.5.0-beta.2
webpack: 5.33.2
react-refresh: 0.10.0
laravel-mix: 6.0.16

An error occurred after upgrading the version from 0.5.0-beta.1 to 0.5.0-beta.2

### PR DESCRIPTION
**Pull request by Austaras**
fixes #354

### CODE REVIEW

**Review by soilSpoon — APPROVED** [review]

**Comment by SamMorrowDrums** [comment]
Can confirm, I finally have ES module live reload in webpack 5 working!!! Thank you. CC people depending on #294

```
npm install --save-dev react-refresh@0.10.0 pmmmwh/react-refresh-webpack-plugin#pull/355/head
```

**Review by SamMorrowDrums — APPROVED** [review]

**Comment by pmmmwh** [comment]
Thanks for the PR, I'll cut a release.

**Review by pmmmwh — APPROVED** [review]

**Comment by pmmmwh** [comment]
Published in `0.5.0-beta.3`.
